services:
  - type: web
    name: wangpeizhao-portfolio
    runtime: static
    branch: main
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    autoDeploy: true
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
